### PR TITLE
Fix deprecated imp module use in py-compile script during build

### PR DESCRIPTION
**Pull request by nategraff-sifive**
Regenerate configure scripts with automake 1.16.2. This fixes the py-compile script's use of the imp module, which has been deprecated in Python 3.4+.

### CODE REVIEW

**Comment by sifivekevin** [comment]
Does this mean I need not update the automake bundled with FS? (The less I need to touch that bundle, the better.)

**Comment by nategraff-sifive** [comment]
> Does this mean I need not update the automake bundled with FS? (The less I need to touch that bundle, the better.)

Are you running `autoreconf` on elf2hex in Freedom Studio? If not, then you should be safe to leave it alone.

**Review by bsousi5 — APPROVED** [review]
LGTM

**Review by sifivekevin — APPROVED** [review]
LGTM too

**Pull request merged**
